#!/bin/bash

# Remove files generated by make commands in the package.json (not actual Make)

targets=(
  'src/modules/prisma/prisma.generated/'
  'src/modules/bundled.gql-bindings.ts'
)

for target in "${targets[@]}"; do
  rm -r "${PWD:?}/$target" 2> /dev/null
  status=$?
  if [ $status -eq 0 ]; then
    echo "[MakeClean] Removed: ${target}"
  fi
done

exit 0
